### ISSUE TITLE
Code sandbox example is error

### ISSUE THREAD

**Issue by Moanrisy** [stivaugoin/gedcom-js#10]
TypeError
crawl is not a function
Object.parse
[https://1r581n3v9q.csb.app/node_modules/parse-gedcom/index.js:22:5]()
Object.parse
[https://1r581n3v9q.csb.app/node_modules/gedcom-js/dist/parse.js:22:38]()
FileReader.fileReader.onload
[/src/index.js:29:28]()
  26 | 
  27 | fileReader.onload = async fileContent => {
  28 |   const { result } = fileContent.currentTarget;
> 29 |   const data = gedcom.parse(result);
     |                      ^
  30 | 
  31 |   this.setState({
  32 |     fileIsLoaded: true,

**Comment by stivaugoin** [comment]
Thanks for reporting @Moanrisy.
I just want to inform you that I'm currently rewrite the lib to not depend on any other parser. Stay tune in the next weeks for a better version.
