### ISSUE TITLE
Not all Gedcom files contain Places

### ISSUE THREAD

**Issue by TomGB** [stivaugoin/gedcom-js#6]
The places should be an optional field, I had to comment out the check for places in `getWeddings.js` to get it working.

**Comment by stivaugoin** [comment]
Thanks @TomGB!

I just have my own gedcom files to test, so I missed a lot of use case.

Feel free to create a PR if you want. Otherwise, I will try to fix that in the next days.

**Comment by frankbracq** [comment]
Hello Steve,

What should  I do to get rid of this error when using attached .ged file?
[lordOfTheRings.ged.zip](https://github.com/stivaugoin/gedcom-js/files/6176432/lordOfTheRings.ged.zip)

Thanks in advance for your help

Frank

**Comment by stivaugoin** [comment]
Hey, sorry for the delay but I was very busy on other projects. I just want to inform you that I'm currently rewrite the lib to not depend on any other parser. Stay tune in the next weeks for a better version. For this reason I will not fix this problem.
