### ISSUE TITLE
genealogit, a project using gedcom-js

### ISSUE THREAD

**Issue by olets** [stivaugoin/gedcom-js#9]
Thought you might be interested to know that I'm using gedcom-js in a little "model genealogy in Git" project https://github.com/olets/genealogit

**Comment by stivaugoin** [comment]
@olets Thanks for sharing! Very interesting, I will take a look soon.

**Comment by olets** [comment]
Was playing with my project a month or so ago and found the oclif aspect wasn't really working :/ But mostly just wanted you to know your project was getting some love
